# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rts-search-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11.7'
  AZURE_WEBAPP_NAME: rts-search-app
  PYTHON_PACKAGE_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
        
      - name: Prepare deployment files
        run: |
          chmod +x app_start.sh
          find . -type f -name "*.sh" -exec dos2unix {} \;

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EACFA96DFCB644FBAE9BA92C1ED1D614 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E196BCEA8CA419B9618661BA44D98EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_24F9FC05C50D4C6691A32CE468A69965 }}

      - name: Configure Azure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group rts_innovate \
              --linux-fx-version "PYTHON|${{ env.PYTHON_PACKAGE_VERSION }}" \
              --startup-file "app_start.sh"
            az webapp config appsettings set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group rts_innovate \
              --settings PYTHON_VERSION=${{ env.PYTHON_VERSION }} SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Stop Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rts_innovate

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          clean: true
          restart: true

      - name: Start Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rts_innovate