# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - rts-search-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: rts-search-app
  PYTHON_VERSION: 3.11.7
  AZURE_RESOURCE_GROUP: rts_innovate

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare shell scripts
        run: |
          find . -name "*.sh" -exec dos2unix {} \;
          find . -name "*.sh" -exec chmod +x {} \;

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Configure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --linux-fx-version "PYTHON|3.11" \
              --startup-file "python -m gunicorn --bind=0.0.0.0:8000 wsgi:app"

            az webapp config appsettings set \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --settings \
                PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
                WEBSITES_PORT=8000 \
                SCM_DO_BUILD_DURING_DEPLOYMENT=true \
                ENABLE_ORYX_BUILD=true
      - name: Stop Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rts_innovate

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          clean: true
          restart: true

      - name: Start Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group rts_innovate